### PR TITLE
fix(checkTagNames): #327 - Tag name autofix confused by adjacent tags

### PR DESCRIPTION
**Pull request by a-nozeret**
This fix assumes that all tagNames are followed with a space, would that be correct?

### CODE REVIEW

**Comment by gajus** [comment]
Please add a text case showing where it was breaking before.

**Comment by a-nozeret** [comment]
@gajus this fix relates to issue #327 where the bug is detailed. Or do you mean something else missing in the PR?

**Comment by gajus** [comment]
> @gajus this fix relates to issue #327 where the bug is detailed. Or do you mean something else missing in the PR?

If you are fixing bug, then previous test cases were not covering some case. To avoid the bug recurring in the future we should add a test case that shows that the bug is no longer present after this fix is added.

**Comment by a-nozeret** [comment]
Sure! done that @gajus

**Pull request merged**
