### PR TITLE
- Add matchDescription for #107

### PR DESCRIPTION
**Pull request by brettz9**
Fixes part of #107.

This is working in my local Node environment, but not with Node 4 which doesn't support Unicode regexes. Can we bump to Node >= 6?

### CODE REVIEW

**Comment by gajus** [comment]
Done

**Comment by brettz9** [comment]
My apologies, it seems that while Unicode regexes (with the 'u' flag) are supported as of 6.0, the property escapes I needed here are not yet available until 10.3. Not a big deal from that angle, as I just wanted it in the default regex to allow for default upper-casing independent of language. Hope you don't mind having made the bump though, as it should make for a lot cleaner code at least, such as allowing destructuring and defaults. I will look to refactor.

**Comment by brettz9** [comment]
Ok, I've refactored to just support English upper-case by default (the config allows one to add one's own regex anyways).

I came across another regex error in another rule (`require-hyphen-before-param-description`) due to it also using a feature not yet supported in Node 6; that is also fixed in this PR.

**Comment by brettz9** [comment]
Btw, thanks for the commit access! Would you like me to do merges and approvals for any I feel comfortable accepting, or reserve my access for minor fixes/tweaks?

**Pull request merged**
