### PR TITLE
Duplicate params

### PR DESCRIPTION
**Pull request by brettz9**
- Report duplicate param names as such

(Behavior noticed missing in comparing with `valid-jsdoc`; #107)

Btw, I'm happy to merge these PRs of mine or others I'm comfortable merging, @gajus , but just would like to know if you have any specific preferred procedures for when I might directly merge and when to submit PRs (or submit a PR and merge it myself)...

### CODE REVIEW

**Comment by gajus** [comment]
> Btw, I'm happy to merge these PRs of mine or others I'm comfortable merging, @gajus , but just would like to know if you have any specific preferred procedures for when I might directly merge and when to submit PRs (or submit a PR and merge it myself)...

For fixes and non-breaking changes, please go ahead and merge the changes yourself (Please still raise PRs as a way of documenting the changes if it is more than one commit).

For new features, breaking changes, just add me as a reviewer please.

**Comment by brettz9** [comment]
I've rebased now if you want to check on whether to approve this new "feature".

**Comment by gajus** [comment]
LGTM

**Pull request merged**
