### PR TITLE
build: make create-readme part of test

### LINKED ISSUE #238: Make `create-readme` part of test
I find the current workflow of generating readme in post-commit sligtly cumbersome. 1. The commit `docs: generate docs` is noisy. 2. Somehow the post-commit script will fail if I am not in the branch master.

How about this workflow:
1. Contributor do their work and run test.
2. Test script generate README (without writing to disk), and check that the generated readme is identical to `/README.md`. If the REAMDE is not up to date, fail test with the message: `Please run "npm run create-readme" to update the docs.`.
3. Contributor run `npm run create-readme`. This script generate README and write it to disk.

This workflow has the benefit that updatedness of README is tested in CI.

What do yo think?

### PR DESCRIPTION
**Pull request by golopot**
closes #238 .

There is one problem. Gitdown will throw error if the current branch is not master. Can you help with this @gajus?

```
Error: Branch ("my-my-branch") definition does not exist in the config.
      at Object.gitinfo.getRemoteUrl (node_modules/gitinfo/dist/gitinfo.js:816:13)
      at Object.gitinfo.getUsername (node_modules/gitinfo/dist/gitinfo.js:868:59)
```

- [x] update when gajus/gitinfo#19 is merged

### CODE REVIEW

**Comment by gajus** [comment]
For what it is worth, that particular error originates from here.

https://github.com/gajus/gitinfo/blob/24dde226da187a2547a2378f669444f47f99eb78/src/gitinfo.js#L54

I am completely overloaded at the moment, but I can take a look Monday morning.

**Comment by golopot** [comment]
The error happens when the current branch does not have a tracking branch. More precisely, when the current branch does not appear in `.git/config`.

**Comment by brettz9** [comment]
@gajus : Do you think you will be able to find some time to investigate this?

**Comment by gajus** [comment]
> @gajus : Do you think you will be able to find some time to investigate this?

The dependent issue has now been resolved thanks to @golopot .

**Comment by brettz9** [comment]
Builds are failing, but I don't know why, even after I forced an empty commit, Travis is showing it as "Commit 0414b85" while Github and local show it as 394db36 (I also don't know if you have more work to do, but thought I'd at least merge and get passing with latest eslint.)

**Comment by golopot** [comment]
Waiting for another pr https://github.com/gajus/gitinfo/pull/19

**Comment by brettz9** [comment]
https://github.com/gajus/gitinfo/pull/19 is no longer blocking. Though I filed https://github.com/gajus/gitdown/pull/55 to ensure the latest updated gitinfo was being used by all, the version range within gitdown will accept the newest version, so if you remove your `node_modules` and `package-lock.json`, and do a fresh local install, you can get the latest gitinfo.

**Comment by brettz9** [comment]
However, doing a Travis rebuild here wasn't enough to get the error to go away, despite the fact that it should now be installing the latest gitinfo...

**Comment by golopot** [comment]
That's expected. Some works is still needed for this pr.

**Comment by golopot** [comment]
This pushed version:
1. Remove post-commit hook for gernerating readme.
2. Add pre-push hook that checks readme is up to date.
3. Move other pre-commit hooks to pre-push hook.
4. Check readme is up to date in ci.

**Comment by brettz9** [comment]
I've rebased... Is this ready to be merged then, @golopot ?

**Comment by golopot** [comment]
Yes

**Comment by brettz9** [comment]
Am bringing this up a bit late, but is there any way we can do the build and check-readme only when on or merging into `master`?

**Pull request merged**
