### PR TITLE
feat(check-param-names, check-property-names): add `enableFixer` option

### PR DESCRIPTION
**Pull request by brettz9**
Allows disabling duplicate fixing.

### CODE REVIEW

**Comment by brettz9** [comment]
> I am more inclined to change to rule to never fix this case, without an option. There are other rules in the ecosystem similar to this case: `no-dupe-keys`, `no-duplicate-case`, and `imoprt/no-duplicate`. They do not provides fixes. The general idea is that "if the fix could break peoples' code, don't fix".

People can review fixes before committing them (and really should), so it can still save them time even if the user wishes to opt in to enable a potentially over-aggressive fixer. And in our case, in the vast majority of cases, at worst it should only strip out a useful comment. Also, these fixers have been in place for some time without complaint--I'm only now giving the opportunity to disable them. I'm ok with a breaking change to change the default though if you want to err on the side of caution.

**Comment by golopot** [comment]
That would be great, thanks. And it should be a minor release. https://github.com/eslint/eslint#semantic-versioning-policy

**Comment by brettz9** [comment]
Sure, though it breaks in the sense of no longer working quite as before, it at least won't lead to more broken builds.

**Comment by brettz9** [comment]
I've switched to the new default (of `enableFixer: false`).

**Comment by brettz9** [comment]
@golopot : It'd be great if you could find time to take a look to see that my latest changes are ok and if this is ready for merging (I've rebased, but the changes were made in the final commit of this PR). I intend to look at fixing #532 tomorrow.)

**Pull request merged**
