### PR TITLE
Test expecting space

### PR DESCRIPTION
**Pull request by brettz9**
- Fix failing test by adding missing space (as added by rule along with newline)

### CODE REVIEW

**Comment by gajus** [comment]
This extra space is going to be stripped by rules declared in `.editorconfig`.

The fix should happen in the rule, i.e. space should not be required.

**Comment by brettz9** [comment]
I guess you mean the space should not be added in the rule rather than not be "required" in the rule. 

I've amended and force-pushed such a change.

**Comment by gajus** [comment]
> I've amended and force-pushed such a change.

Whats the reason you are using force push?

**Comment by gajus** [comment]
Thank you

**Comment by brettz9** [comment]
Sure, my pleasure... I force-pushed as I recall getting rejected from pushing with amended commits (and you'd otherwise have my original commit, undoing that commit, and the second commit all together)...

**Pull request merged**
