### PR TITLE
ci: Add GitHub Action for linting

### PR DESCRIPTION
**Pull request by nschonni**
GitHub Actions have built-in problem matchers for ESLint from setup-node to show warnings/errors on the PR file tab

### CODE REVIEW

**Comment by nschonni** [comment]
You can see a run here https://github.com/nschonni/eslint-plugin-jsdoc/runs/4578250445?check_suite_focus=true, but there are failures from some formatting issues.

**Comment by nschonni** [comment]
Actually, easier to see the problem matcher in action on this PR https://github.com/nschonni/eslint-plugin-jsdoc/pull/1/files

**Comment by gajus** [comment]
We should migrate entirely to GitHub Actions.

https://github.com/gajus/table could serve as a recent example of such migration.

**Comment by nschonni** [comment]
@gajus do you want me to just use this PR to fully migrate or take it in pieces like this one?

**Comment by gajus** [comment]
Don't see a problem with adding it all to this PR if you are open to it.

**Comment by nschonni** [comment]
I ended up creating https://github.com/gajus/eslint-plugin-jsdoc/pull/824 as an alternate with the full migration

**Comment by brettz9** [comment]
Closing in favor of #824

**Pull request closed without merging**
