### PR TITLE
Update docs for typo and readability

### PR DESCRIPTION
**Pull request by Twoody**
There was an improper sentence that needed decoded. The use of a bulleted-list also helped with the understanding of what the author was intending to say.

### CODE REVIEW

**Comment by brettz9** [comment]
Hi,

Thanks for the fix.

We really need this applied to `/.README/README.md` and then have `npm run create-readme` run locally to automatically build the main `/README.md`. Let me know if you are not able to do this.

**Comment by Twoody** [comment]
@brettz9 totally in my realm of capabilities. I'll get that going in a few minutes.

**Comment by Twoody** [comment]
@brettz9  Does the team do squash's on the merge, or is that something expected on my end too?

**Comment by brettz9** [comment]
We tend to squash yes, so all good, thanks again!

**Pull request merged**
