### PR TITLE
fix: add names to flat configs

### PR DESCRIPTION
**Pull request by voxpelli**
See https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions and eg https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/459

Improves presentation in the config inspector: https://github.com/eslint/config-inspector

### CODE REVIEW

**Comment by brettz9** [comment]
@voxpelli : A belated thanks for this PR. Do you think we should prefix the name with `jsdoc/` though? Seems the docs suggest incorporating the plugin name too.

**Comment by voxpelli** [comment]
> For example, if you are creating a configuration object for a plugin named eslint-plugin-example, you might add name to the configuration objects with the example/ prefix

@brettz9 🙏 that's what I'm reading in the docs?

**Comment by brettz9** [comment]
Ok, I can add that

**Comment by brettz9** [comment]
Released in v48.2.12.

**Pull request merged**
