### PR TITLE
fixed typo: 'getters' -> 'setters'

### PR DESCRIPTION
**Pull request by DerZyklop**
I changed one character in the README.md. I guess it was a typo caused by copy paste.

### CODE REVIEW

**Comment by DerZyklop** [comment]
Github tells me there are 15,730 additions and 15,730 deletions. I only changed one character. 
I don’t know whats happening here. 
¯\_(ツ)_/¯

**Comment by brettz9** [comment]
We build that README from assorted other files, so we need that fixed anyways. But I searched for "getters" in our source files and fixed them and the built file. Thanks for the report!

**Comment by brettz9** [comment]
We build that README from assorted other files, so we need that fixed anyways. But I searched for "getters" in our source files and fixed them and the built file. Thanks for the report!

**Comment by brettz9** [comment]
We build that README from assorted other files, so we need that fixed anyways. But I searched for "getters" in our source files and fixed them and the built file. Thanks for the report!

**Comment by brettz9** [comment]
We build that README from assorted other files, so we need that fixed anyways. But I searched for "getters" in our source files and fixed them and the built file. Thanks for the report!

**Comment by brettz9** [comment]
We build that README from assorted other files, so we need that fixed anyways. But I searched for "getters" in our source files and fixed them and the built file. Thanks for the report!

**Pull request closed without merging**
