### PR TITLE
Travis CI: Test on latest Node.js v4.x.x and v6.x.x branches

### PR DESCRIPTION
**Pull request by ntwb**
Currently these latest versions are `4.4.7` for the 4.x branch and `6.2.2` for the 6.x branch

### CODE REVIEW

**Comment by ntwb** [comment]
@gajus I've refreshed this pull request to now test NodeJS 4 & 6, i.e. "LTS" and "stable"

**Comment by gajus** [comment]
Whats the reason for excluding version 5?

**Comment by ntwb** [comment]
NodeJS maintain 2 branches, "LTS" (Long Term Support) and "Stable"

The 5.x and 6.x branches are part of the "stable" branch, it's just semantic versioning going on and hence why 5.x is superseded by 6.x.

**Comment by gajus** [comment]
You mean to say there were no breaking changes between v5 and v6?

I assume there were. Otherwise, it would not be semantic versioning. In which case, any changes to this library need to pass the tests against v5 and v6.

**Comment by ntwb** [comment]
I've added 5.x back into the job matrix

**Pull request merged**
