### PR TITLE
chore(.husky): remove unnecessary .gitignore

### PR DESCRIPTION
**Pull request by Fdawgs**
`.husky/.gitignore` is no longer required as of [husky 7.0.0](https://github.com/typicode/husky/releases/tag/v7.0.0), and the devDep is currently at ^7.0.4.

### CODE REVIEW

**Comment by brettz9** [comment]
Thanks for the PR!

**Comment by brettz9** [comment]
For some reason, Atom's `.gitignore` is showing things as though there has been a change.

image

Even if this is an Atom bug, I find it strange that this particular commit would cause problems. Is the underscore directory no longer needed too, do you know?

**Comment by Fdawgs** [comment]
`.husky/_/` is created when `husky install` is ran and contains the script that the hooks use, so it is needed yes.
Seems like an Atom bug. 😞

**Pull request merged**
