### PR TITLE
Added rule: require-example

### LINKED ISSUE #34: [Feature request] require-example-*
This would be similar in style to the `require-param-*` family of rules.

### PR DESCRIPTION
**Pull request by kunagpal**
Resolves #34

### CODE REVIEW

**Comment by gajus** [comment]
Please update the documentation in https://github.com/gajus/eslint-plugin-jsdoc/tree/master/.README.

**Comment by kunagpal** [comment]
Will do 👍

**Comment by kunagpal** [comment]
@gajus Ping

**Comment by gajus** [comment]
Oops. Sorry for the delay.

Thank you.

**Comment by ntwb** [comment]
Looks like the docs for the main README were not in this PR?
https://github.com/gajus/eslint-plugin-jsdoc/blob/master/README.md

**Comment by gajus** [comment]
Fixed.

**Pull request merged**
